name: Linux 64-bit
run-name: ${{github.actor}} is testing out GitHub Actions
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
          #os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: sudo apt update && sudo apt install fp-compiler moreutils
    - name: retrieve mads
      run: git clone --depth 1 --branch 2.1.6 https://github.com/tebe6502/Mad-Assembler mads
    - name: build mads
      run: |
        fpc -Mdelphi -vh -O3 -omads/mads mads/mads.pas
        echo "${PWD}/mads" >> $GITHUB_PATH
    - name: make test
      run: make -j`nproc` test

    - name: Archive production artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: linux64-build-failure
        path: xex
