name: CI Ubuntu x86_64
run-name: ${{github.actor}} is testing out GitHub Actions
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: sudo apt update && sudo apt install fp-compiler moreutils
    - name: retrieve mads
      run: git clone --depth 1 --branch 2.1.6 https://github.com/tebe6502/Mad-Assembler mads
    - name: build mads
      run: |
        fpc -Mdelphi -vh -O3 -omads/mads mads/mads.pas
        echo "${PWD}/mads" >> $GITHUB_PATH
    - name: make test
      run: make -j`nproc` test
