name: macOS x86_64
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-13]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build and test
      run: |
        brew install fpc md5sha1sum
        git clone --depth 1 --branch 2.1.6 https://github.com/tebe6502/Mad-Assembler mads
        fpc -Mdelphi -vh -O3 -omads/mads mads/mads.pas
        export PATH=$PATH:`pwd`/mads
        make -j`sysctl -n hw.ncpu` test

    - name: Archive production artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-x86_64-build-failure
        path: xex
