name: Windows 64-bit
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019]
          #os: [windows-2019,windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Cygwin
      uses: cygwin/cygwin-install-action@master
      with:
        packages: gcc-g++,make,xxd,git,cygwin-devel,zip,unzip,wget
        add-to-path: false
        platform: x86_64
    - name: build saprtools with cygwin
      shell: C:\cygwin\bin\bash.exe --login -o igncr -eo pipefail '{0}'
      run: |
        set -e
        export PATH=/usr/bin
        export MSYSTEM=
        # This is actually a 32-bit binary
        wget -O/usr/bin/mads https://github.com/tebe6502/Mad-Assembler/raw/refs/tags/2.1.6/bin/windows_x86_64/mads.exe
        chmod 755 /usr/bin/mads
        cd "${{github.workspace}}" && make -j`nproc` test

    - name: Archive production artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: win64-build-failure
        path: xex
